src/main.ts
=> remove metadata from options since we weren't using it anyways

src/main.ts, src/protocol.ts, src/types.ts
Added request types for JobHistory requests. Have another PR here to go with it here - https://github.com/Microsoft/sqlopsstudio/pull/923 . The backend in sqltoolsservice is done.
=> added requests for job history

package.json, src/main.ts
Part of the set of changes needed to support using generic SQL queries to retrieve EditData rows.
=> Add new queryString argument to initializeEdit function.

src/main.ts, src/protocol.ts
Related change was completed and merged previously Microsoft/sqltoolsservice#684
After this PR completed, i'll make another PR for Microsoft/azuredatastudio#1387
=> Methods added for the exporting result as Xml

package.json, src/main.ts, src/protocol.ts, src/types.ts
implement the disconnect session request.
the version is bumped up to 0.2.15 because I have used the numbers in between for testing.
=> implement disconnect session

package.json, src/codeConverter.ts, src/main.ts, src/protocol.ts, src/protocolConverter.ts, src/types.ts, src/typing/azdata.proposed.d.ts, yarn.lock
This should be a non-functional change that renames from 'sqlops' to 'azdata', and adds azdata.proposed.d.ts while we finish porting DMP definitions to stable.
=> Update dataprotocol to use azdata module

package.json, src/codeConverter.ts, src/main.ts, src/protocol.ts, src/protocolConverter.ts, tslint.json, yarn.lock
Adding TSLinting to the repo - primarily for use by TSA scans. Fixed up some linting issues as well.
=> Add TSLinting for TSA scans

package.json, yarn.lock
Addresses security vulnerabilities flagged by https://github.com/microsoft/sqlops-dataprotocolclient/network/alerts
=> Update VSCode package to address security vulnurabilities

lib/main.js, lib/protocol.d.ts, package.json, src/main.ts, src/protocol.ts
port the changes to release branch and update the compiled files
=> port changes to release branch

src/azdata.proposed.d.ts, src/main.ts, src/protocol.ts
This is in conjunction with https://github.com/microsoft/sqltoolsservice/pull/1227 and an upcoming PR for ADS.
=> Added changeConnectionUri for Query command.

yarn.lock
This is to account for the bump to azdata
=> update to yarn.lock

src/types.ts
Companion PR for: https://github.com/microsoft/azuredatastudio/pull/20511
=> Update to connection complete params descriptions for ErrorMessage and Messages

.github/workflows/ci.yml, package.json, src/azdata.d.ts, src/azdata.proposed.d.ts, yarn.lock
Compile is currently broken because the ConnectionInfo types here don't match the ones from `@types/azdata` (they were updated in https://github.com/microsoft/sqlops-dataprotocolclient/pull/66). This is a temporary fix until the typings get updated next release.
Also fixing up the CI workflow to trigger on the new default branch (main).
=> Update to latest typings to fix compile

package.json, src/main.ts
for: https://github.com/microsoft/azuredatastudio/issues/21091
the exception was swallowed by the dataprotocol-client.
=> throw the scripting error

package.json
Intended release will include https://github.com/microsoft/sqlops-dataprotocolclient/pull/79
=> Bumping version to 1.3.3

package.json, src/main.ts, yarn.lock
Includes some commits that were squash-merged into release to reconcile the commit histories.
=> Porting changes for 1.3.3

lib/codeConverter.js, lib/main.js, lib/protocol.d.ts, lib/protocol.js, lib/types.d.ts, lib/types.js, package.json, src/azdata.proposed.d.ts, src/codeConverter.ts, src/main.ts, src/protocol.ts, src/types.ts, tslint.json, yarn.lock
cherry-pick #85 and #86 to release branch and also update the compiled js files.
=> copy result handler

lib/main.js, lib/protocol.d.ts, src/azdata.proposed.d.ts, src/main.ts, src/protocol.ts
ports https://github.com/microsoft/sqlops-dataprotocolclient/pull/93 to release branch
=> [Port] Add copy results return value

package.json, src/azdata.proposed.d.ts, src/main.ts, src/types.ts
The data protocol counterpart to this STS PR: https://github.com/microsoft/sqltoolsservice/pull/2238
=> Add ability to only show folders in File Browser dialogs

lib/main.js, lib/types.d.ts, package.json, src/azdata.proposed.d.ts, src/main.ts, src/types.ts
Porting over this commit and its related build files changes: https://github.com/microsoft/sqlops-dataprotocolclient/commit/9f75b1003a381ba417977d45f03ad6bfdb4aff51
=> Port file dialog changes to release branch

src/azdata.proposed.d.ts
Part of PR for ADS SPID display.
=> Add SPID to ConnectionInfoSummary
